### ISSUE TITLE
Allow use of stack[] variables in stack.cfg

### ISSUE THREAD

**Issue by andy-stevens** [bbinet/pillarstack#6] opened 2016-04-25 12:24 UTC
It would be great to be able to use stack[] variables in the configuration files for PillarStack.

Also currently the use of multiple stack.cfg files does to appear to be working as expected.  I would have assumed that, for example, given two configuration files ..... any of the variables evaluated in the first config file will be fully available (via stack[] or pillar[]) in the second configuration file.

But this does not appear to be working...

**Comment by bbinet** [comment] 2016-04-26 15:12
On 25 April 2016 at 14:24, Andy Stevens notifications@github.com wrote:

> It would be great to be able to use stack[] variables in the configuration
> files for PillarStack.
> 
> You should already be able to use stack variables in the configuration
> files for PillarStack (only the stack variables that have been computed
> from the previous configuration files).
> As you can see we pass the stack variable when rendering the configuration
> files:
> https://github.com/bbinet/pillarstack/blob/master/stack.py#L52
> 
> Also currently the use of multiple stack.cfg files does to appear to be
> working as expected. I would have assumed that, for example, given two
> configuration files ..... any of the variables evaluated in the first
> config file will be fully available (via stack[] or pillar[]) in the second
> configuration file.

This should also be the case, as you can see:
https://github.com/bbinet/pillarstack/blob/master/stack.py#L54

Can you provide your configuration file and pillarstack data files?

**Comment by skob** [comment] 2016-10-26 16:09
+1 to request... For example

```
cat ./ext_pillar/stack.cfg
minions/{{ minion_id }}.yml
{% if stack['env'] == 'test' %}
mine.yml
{% endif %}
```

**Comment by bbinet** [comment] 2016-10-27 09:28
It should work if 'env' is defined in pillarstack from a previous stack.cfg config file: you should have at least 2 stack.cfg config files for this to work.

**Comment by skob** [comment] 2016-10-27 11:57
```
cat /etc/salt/master.d/central.conf
...
pillar_merge_lists: True
pillar_roots:
  base:
    - /opt/salt/pillar
ext_pillar_first: True
ext_pillar:
  - stack:
    - /opt/salt/ext_pillar/stack.cfg
    - /opt/salt/ext_pillar/stack_with_envs.cfg
```

```
cat /opt/salt/ext_pillar/stack.cfg
minions/{{ minion_id }}.yml
```

```
cat /opt/salt/ext_pillar/minions/central.yml
ext_env: prod
ext_roles:
  - uac
  - uan
```

```
cat /opt/salt/ext_pillar/stack_with_envs.cfg
{%- for role in stack['ext_role'] %}
test.yml
{% endfor %}
```

```
cat /opt/salt/ext_pillar/test.yml
eeeeeeee: vvvvvv
```

```
systemctl restart salt-master ; systemctl restart salt-minion ; salt-call saltutil.sync_all ; salt-call pillar.ls | grep eeeeeeee | wc -l
0
```

**Comment by bbinet** [comment] 2016-12-22 10:23
Sorry for the delay.
After investigation, this seems to be related to a whitespace issue.
I will submit a PR to fix this soon.

**Comment by bbinet** [comment] 2016-12-22 10:32
@phtx3 @skob could you test pull request #20 and confirm it actually fix this issue?

**Comment by skob** [comment] 2016-12-22 10:33
@bbinet , sorry , I'm not able test your patch now :-/
Please leave issue open, I'l comment later...

**Comment by bbinet** [comment] 2016-12-22 10:55
@skob @phtx3 I could reproduce this issue and I've tested pull request #20 locally which actually fix the issue.
So I'm going to merge the pull request and close this issue: please reopen if needed.

**Closed as completed** 2016-12-22 10:55 UTC
